version: '3'

services:
  mastermind_nginx:
    image: nginx:latest
    volumes:
      - static_volume:/app/static
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/web.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    restart: on-failure
    depends_on:
      - mastermind_api

  mastermind_postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=mastermind
      - POSTGRES_PASSWORD=mastermind_password
      - POSTGRES_DB=mastermind_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: on-failure

  mastermind_api:
    build: .
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - static_volume:/app/static
      - ./mastermind:/app
    environment:
      - DATABASE_NAME=mastermind_db
      - DATABASE_USER=mastermind
      - DATABASE_PASSWORD=mastermind_password
      - DATABASE_HOST=mastermind_postgres
      - DATABASE_PORT=5432
      - WAIT_HOSTS=mastermind_postgres:5432
    depends_on:
      - mastermind_postgres

volumes:
  static_volume: