# Generated by Django 2.2.9 on 2020-01-25 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodePeg",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot1",
                    models.IntegerField(
                        choices=[
                            (1, "Yellow"),
                            (2, "Blue"),
                            (3, "Purple"),
                            (4, "Orange"),
                            (5, "Green"),
                            (6, "Red"),
                        ]
                    ),
                ),
                (
                    "slot2",
                    models.IntegerField(
                        choices=[
                            (1, "Yellow"),
                            (2, "Blue"),
                            (3, "Purple"),
                            (4, "Orange"),
                            (5, "Green"),
                            (6, "Red"),
                        ]
                    ),
                ),
                (
                    "slot3",
                    models.IntegerField(
                        choices=[
                            (1, "Yellow"),
                            (2, "Blue"),
                            (3, "Purple"),
                            (4, "Orange"),
                            (5, "Green"),
                            (6, "Red"),
                        ]
                    ),
                ),
                (
                    "slot4",
                    models.IntegerField(
                        choices=[
                            (1, "Yellow"),
                            (2, "Blue"),
                            (3, "Purple"),
                            (4, "Orange"),
                            (5, "Green"),
                            (6, "Red"),
                        ]
                    ),
                ),
                ("is_solution", models.BooleanField(default=False)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_pegs",
                        to="game.Game",
                    ),
                ),
            ],
        ),
    ]
